const BASE = {
  ON_FOCUS: 'ON_FOCUS',
  OUT_FOCUS: 'OUT_FOCUS',
  ON_PREVIEW: 'ON_PREVIEW',
  OUT_PREVIEW: 'OUT_PREVIEW',
  ON_HOME_PAGE: 'ON_HOME_PAGE',
  OUT_HOME_PAGE: 'OUT_HOME_PAGE',
  SET_COLOR: 'SET_COLOR',
  SET_FILTER: 'SET_FILTER',
}

const SUCCESS = {
}

const ERROR = {
}

export default {
  BASE,
  SUCCESS,
  ERROR,
}