const BASE = {
  ON_FOCUS: 'ON_FOCUS',
  OUT_FOCUS: 'OUT_FOCUS',
  ON_PREVIEW: 'ON_PREVIEW',
  OUT_PREVIEW: 'OUT_PREVIEW',
  ON_HOME_PAGE: 'ON_HOME_PAGE',
  OUT_HOME_PAGE: 'OUT_HOME_PAGE',
  ON_REDIRECT: 'ON_REDIRECT',
  OUT_REDIRECT: 'OUT_REDIRECT',
}

const SUCCESS = {
}

const ERROR = {
}

export default {
  BASE,
  SUCCESS,
  ERROR,
}